import Header from "@/components/Header";
import Hero from "@/components/Hero";
import OverviewSection from "@/components/OverviewSection.jsx";
import Section1 from "@/components/Section1.jsx";
import Section2 from "@/components/Section2.jsx";
import Section3 from "@/components/Section3.jsx";
import Head from "next/head";
import DarkLogoRounded from "../public/assets/Logos/Svgs/black-logo-rounded-border.svg";
import ConversionExampleSection from "@/components/ConversionExampleSection.jsx";
import HomeToolsExamples from "@/components/HomeToolsExamples.jsx";
import Pricing from "@/components/Pricing.jsx";
import Footer from "@/components/Footer.jsx";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cssnovo - Your CSS Second Brain - AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={DarkLogoRounded.src} />
      </Head>
      <Header />
      <Hero />
      <OverviewSection />
      <Section1 />
      <Section2 />
      <Section3 />
      <ConversionExampleSection />
      <HomeToolsExamples />
      <Pricing />
      <Footer />
    </div>
  );
}
